name: LabelCaptureSimpleSample
description: A basic Label Capture setup to scan labels with barcodes.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_core:
    '>=8.0.0 <8.0.1'
  scandit_flutter_datacapture_barcode:
    '>=8.0.0 <8.0.1'
  scandit_flutter_datacapture_label:
    '>=8.0.0 <8.0.1'
  scandit_flutter_datacapture_label_text:
    '>=8.0.0 <8.0.1'
  permission_handler: 12.0.1
  flutter_bloc: ^9.1.1

flutter:
  uses-material-design: true