name: IdCaptureSimpleSample
description: A basic ID Capture setup to scan front of ID Cards and barcodes from AAMVA documents.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_id:
    '>=8.2.0 <8.2.1'
  permission_handler: 12.0.1
  intl: ^0.19.0

flutter:
  uses-material-design: true
