name: USDLVerificationSample
description: ID Verification setup for US driver's licenses.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_id:
    '>=8.1.1 <8.1.2'
  scandit_flutter_datacapture_id_aamva_barcode_verification:
    '>=8.1.1 <8.1.2'
  permission_handler: 12.0.1
  intl: ^0.19.0

flutter:
  uses-material-design: true
