name: MatrixScanARSimpleSample
description: "Very simple sample which shows how you can use MatrixScan AR to show product information with the Scandit Data Capture SDK."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_barcode:
    '>=8.0.0 <8.0.1'
  scandit_flutter_datacapture_core:
    '>=8.0.0 <8.0.1'
  permission_handler: 12.0.1

flutter:
  uses-material-design: true
