name: RestockingSample
description: ID Verification setup for US driver's licenses.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_barcode:
    '>=8.1.0 <8.1.1'
  permission_handler: 12.0.1

flutter:
  uses-material-design: true

