name: BarcodeCaptureSimpleSample
description: Basic sample that uses the camera to read a single barcode.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_barcode:
    '>=8.0.0 <8.0.1'
  permission_handler: 12.0.1

flutter:
  uses-material-design: true
