name: ListBuildingSample
description: A basic sample that demonstrates how to populate a list of scanned barcodes using the Scandit SparkScan API.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_barcode:
    '>=8.0.0 <8.0.1'
  permission_handler: 12.0.1
  intl: ^0.18.1

flutter:
  uses-material-design: true
